language: python
python:
  - "2.7"
  - "3.4"
install: "pip install -r requirements.txt"
script: nosetests --with-coverage --cover-package=ancestral_state tests/test_all/test_all.py
after_success:
  - coveralls

