language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install: "pip install -r requirements.txt"
script:
  - py.test tests/ --pep8 ot_service_wrapper -v --cov ot_service_wrapper --cov-report term-missing
after_success:
  - coveralls

