dist: xenial
language: python
os: linux
python:
  - "3.5"
  - "3.6"
  - "3.7"
before_install:
  - sudo add-apt-repository --yes ppa:ubuntugis/ppa
  - sudo apt-get --quiet update
  - sudo apt-get install --yes libgdal-dev gdal-bin python-gdal
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal
install: 
  - pip install GDAL==`gdal-config --version`
  - pip install -r requirements.txt
script:
  - py.test tests/ --pep8 biotaphy -v --cov biotaphy --cov-report term-missing
after_success:
  - coveralls
jobs:
  include:
  - stage: deploy
    python: '3.7'
    before_install:
    - sudo add-apt-repository --yes ppa:ubuntugis/ppa
    - sudo apt-get --quiet update
    - sudo apt-get install --yes libgdal-dev gdal-bin python-gdal
    - export CPLUS_INCLUDE_PATH=/usr/include/gdal
    - export C_INCLUDE_PATH=/usr/include/gdal
    install:
    - pip install GDAL==`gdal-config --version`
    - pip install -r requirements.txt
    before_deploy:
    - python setup.py sdist bdist_wheel
    deploy:
      provider: releases
      skip_cleanup: true
      api_key:
        secure: QDuzk82SLjqwTobBTN364iICEKvQNBpDxizqfGM/gGyAayJghPhNVBgJBIgbdgSIg1I4om5rPsnqd+qwPPjJz7vSFQPM8voJII/Y9muToo90gSTJoLXoeOHQNUfF/OHZLm3FPHCz309joAq8lxkEVntfkaNLGALR+83Neubnr0cSjlbIuDbgcCrLGz+aokCJ9ayxH4kIf9x9w2o8kuzkKeicinLq5uoDns0Io6qokQu0XvUZphHdA/WQehCT4u5PJ9LMjahbrAMvCfYVuDOZDB6H9TrZMJmvXh7ZRelAxKvNemIooY8acIOjyEtmaZCgNg2vf51a5FHkOtJRnvgBJS5ivKdxUG0d/awXrROcnbsdIvl0uuzon4qTk6XMwuprtr+49qN2u6UfBwb6DUrOX3jK+8JZmKdFI/Jou90TSehgmHKN+HXcr8pzW/glpNXj4ooxL8k9secXHNMBv7YF7u+Ri+sAGiss/lIjAhzFf8EPI/oRFLcqPMdgX+zCOxm/GedS5Tt1lFTyZp/3epZ2sXozvXuKYu3Hdqa4LzH+sPgV6OxKDmfVwiexwqNDg/k7qO3CQyMAVzEImIFCnh6NxT6cYFx82DxPLRDI0IYy5p8/OwCi5xawsJ8OIYoXmPoAld3OQI3YJ5ab+4O+4KQMHPb54Frol3jt1fJJ5oAiEEE=
      file_glob: true
      file: dist/*
      on:
        tags: true
        repo: biotaphy/BiotaPhyPy
      skip_cleanup: 'true'

