language: python
python:
  - "2.7"
  - "3.4"
  - "3.6"
install: "pip install -r requirements.txt"
script:
  - py.test tests/ --pep8 ancestral_reconstruction -v --cov ancestral_reconstruction --cov-report term-missing
after_success:
  - coveralls

