name: biotaphy
channels:
  - conda-forge
dependencies:
  - numpy
  - gdal
  - libspatialindex
  - rtree
  - matplotlib
  - sphinx-autoapi
  - scipy
  - defusedxml
  - coverage
  - coveralls
  - pytest
  - pytest-cov
  - pip=21.3.1
  - pip:
    - sphinx-rtd-theme
    - dendropy
    - specify-lmpy
